# Guest OS timezone
timezone: Europe/Warsaw

# Are we need check box updates for every 'vagrant up'?
box_check_update: true

# Virtual machine name
machine_name: welltoc

# Virtual machine IP
ip: 192.168.5.50

# Virtual machine CPU cores number
cpus: 4

# Virtual machine RAM
memory: 4096
